//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MurMurParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMurMurParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class MurMurParserBaseListener : IMurMurParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.murmur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMurmur([NotNull] MurMurParser.MurmurContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.murmur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMurmur([NotNull] MurMurParser.MurmurContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] MurMurParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] MurMurParser.TagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] MurMurParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] MurMurParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] MurMurParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] MurMurParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.fastPickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFastPickBlock([NotNull] MurMurParser.FastPickBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.fastPickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFastPickBlock([NotNull] MurMurParser.FastPickBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickBlock([NotNull] MurMurParser.PickBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickBlock([NotNull] MurMurParser.PickBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] MurMurParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] MurMurParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] MurMurParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] MurMurParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] MurMurParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] MurMurParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] MurMurParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] MurMurParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.commandId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandId([NotNull] MurMurParser.CommandIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.commandId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandId([NotNull] MurMurParser.CommandIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickCommand([NotNull] MurMurParser.PickCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickCommand([NotNull] MurMurParser.PickCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickThisCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickThisCommand([NotNull] MurMurParser.PickThisCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickThisCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickThisCommand([NotNull] MurMurParser.PickThisCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.menuCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMenuCommand([NotNull] MurMurParser.MenuCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.menuCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMenuCommand([NotNull] MurMurParser.MenuCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.ifCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfCommand([NotNull] MurMurParser.IfCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.ifCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfCommand([NotNull] MurMurParser.IfCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.endCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndCommand([NotNull] MurMurParser.EndCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.endCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndCommand([NotNull] MurMurParser.EndCommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
