//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MurMurParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MurMurParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IMurMurParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.murmur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMurmur([NotNull] MurMurParser.MurmurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTag([NotNull] MurMurParser.TagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] MurMurParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] MurMurParser.TextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.fastPickBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFastPickBlock([NotNull] MurMurParser.FastPickBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickBlock([NotNull] MurMurParser.PickBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] MurMurParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] MurMurParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MurMurParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] MurMurParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.commandId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommandId([NotNull] MurMurParser.CommandIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickCommand([NotNull] MurMurParser.PickCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickThisCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickThisCommand([NotNull] MurMurParser.PickThisCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.menuCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenuCommand([NotNull] MurMurParser.MenuCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.ifCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfCommand([NotNull] MurMurParser.IfCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.endCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndCommand([NotNull] MurMurParser.EndCommandContext context);
}
