//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\dev\murmur\MurMur\MurMur\Grammar\MurMurParser.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MurMur.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MurMurParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public interface IMurMurParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpression([NotNull] MurMurParser.StringExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>methodOrVariableExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodOrVariableExpression([NotNull] MurMurParser.MethodOrVariableExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] MurMurParser.AdditiveExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberExpression([NotNull] MurMurParser.NumberExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>assignExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignExpression([NotNull] MurMurParser.AssignExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>comparissonExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparissonExpression([NotNull] MurMurParser.ComparissonExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>methodExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodExpression([NotNull] MurMurParser.MethodExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>priorityExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPriorityExpression([NotNull] MurMurParser.PriorityExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>multiplicationExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicationExpression([NotNull] MurMurParser.MultiplicationExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>booleanExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExpression([NotNull] MurMurParser.BooleanExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.murmur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMurmur([NotNull] MurMurParser.MurmurContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTag([NotNull] MurMurParser.TagContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] MurMurParser.BlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickBlock([NotNull] MurMurParser.PickBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.menuBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenuBlock([NotNull] MurMurParser.MenuBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlock([NotNull] MurMurParser.IfBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] MurMurParser.LineContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.lineFragment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineFragment([NotNull] MurMurParser.LineFragmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.inlineIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineIfBlock([NotNull] MurMurParser.InlineIfBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.inlineIfTrueFragment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineIfTrueFragment([NotNull] MurMurParser.InlineIfTrueFragmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.inlineIfFalseFragment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineIfFalseFragment([NotNull] MurMurParser.InlineIfFalseFragmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.menuSubBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenuSubBlock([NotNull] MurMurParser.MenuSubBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickThisBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickThisBlock([NotNull] MurMurParser.PickThisBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.simpleCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleCommand([NotNull] MurMurParser.SimpleCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.multiLineCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiLineCommand([NotNull] MurMurParser.MultiLineCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] MurMurParser.StringContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MurMurParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] MurMurParser.ParamsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickCommand([NotNull] MurMurParser.PickCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.pickThisCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPickThisCommand([NotNull] MurMurParser.PickThisCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.menuCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenuCommand([NotNull] MurMurParser.MenuCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.menuOptionCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenuOptionCommand([NotNull] MurMurParser.MenuOptionCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.ifCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfCommand([NotNull] MurMurParser.IfCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.elseCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseCommand([NotNull] MurMurParser.ElseCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.endCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndCommand([NotNull] MurMurParser.EndCommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MurMurParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] MurMurParser.DeclarationContext context);
}
} // namespace MurMur.Grammar
