//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\dev\murmur\MurMur\MurMur\Grammar\MurMurParser.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MurMur.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMurMurParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public partial class MurMurParserBaseListener : IMurMurParserListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringExpression([NotNull] MurMurParser.StringExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringExpression([NotNull] MurMurParser.StringExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>methodOrVariableExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodOrVariableExpression([NotNull] MurMurParser.MethodOrVariableExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>methodOrVariableExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodOrVariableExpression([NotNull] MurMurParser.MethodOrVariableExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>additionExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditionExpression([NotNull] MurMurParser.AdditionExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>additionExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditionExpression([NotNull] MurMurParser.AdditionExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberExpression([NotNull] MurMurParser.NumberExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberExpression([NotNull] MurMurParser.NumberExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>assignExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignExpression([NotNull] MurMurParser.AssignExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>assignExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignExpression([NotNull] MurMurParser.AssignExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>comparissonExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparissonExpression([NotNull] MurMurParser.ComparissonExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>comparissonExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparissonExpression([NotNull] MurMurParser.ComparissonExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>methodExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodExpression([NotNull] MurMurParser.MethodExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>methodExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodExpression([NotNull] MurMurParser.MethodExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>multiplicationExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicationExpression([NotNull] MurMurParser.MultiplicationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplicationExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicationExpression([NotNull] MurMurParser.MultiplicationExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>booleanExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanExpression([NotNull] MurMurParser.BooleanExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>booleanExpression</c>
	/// labeled alternative in <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanExpression([NotNull] MurMurParser.BooleanExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.murmur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMurmur([NotNull] MurMurParser.MurmurContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.murmur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMurmur([NotNull] MurMurParser.MurmurContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] MurMurParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] MurMurParser.TagContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] MurMurParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] MurMurParser.BlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickBlock([NotNull] MurMurParser.PickBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickBlock([NotNull] MurMurParser.PickBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.menuBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMenuBlock([NotNull] MurMurParser.MenuBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.menuBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMenuBlock([NotNull] MurMurParser.MenuBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlock([NotNull] MurMurParser.IfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlock([NotNull] MurMurParser.IfBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] MurMurParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] MurMurParser.LineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.lineFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineFragment([NotNull] MurMurParser.LineFragmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.lineFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineFragment([NotNull] MurMurParser.LineFragmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.inlineIfBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineIfBlock([NotNull] MurMurParser.InlineIfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.inlineIfBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineIfBlock([NotNull] MurMurParser.InlineIfBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.inlineIfTrueFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineIfTrueFragment([NotNull] MurMurParser.InlineIfTrueFragmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.inlineIfTrueFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineIfTrueFragment([NotNull] MurMurParser.InlineIfTrueFragmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.inlineIfFalseFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineIfFalseFragment([NotNull] MurMurParser.InlineIfFalseFragmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.inlineIfFalseFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineIfFalseFragment([NotNull] MurMurParser.InlineIfFalseFragmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.menuSubBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMenuSubBlock([NotNull] MurMurParser.MenuSubBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.menuSubBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMenuSubBlock([NotNull] MurMurParser.MenuSubBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.fastPickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFastPickBlock([NotNull] MurMurParser.FastPickBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.fastPickBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFastPickBlock([NotNull] MurMurParser.FastPickBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickThisBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickThisBlock([NotNull] MurMurParser.PickThisBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickThisBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickThisBlock([NotNull] MurMurParser.PickThisBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] MurMurParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] MurMurParser.CommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] MurMurParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] MurMurParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] MurMurParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] MurMurParser.ParamsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickCommand([NotNull] MurMurParser.PickCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickCommand([NotNull] MurMurParser.PickCommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.pickThisCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPickThisCommand([NotNull] MurMurParser.PickThisCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.pickThisCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPickThisCommand([NotNull] MurMurParser.PickThisCommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.menuCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMenuCommand([NotNull] MurMurParser.MenuCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.menuCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMenuCommand([NotNull] MurMurParser.MenuCommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.menuOptionCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMenuOptionCommand([NotNull] MurMurParser.MenuOptionCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.menuOptionCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMenuOptionCommand([NotNull] MurMurParser.MenuOptionCommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.ifCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfCommand([NotNull] MurMurParser.IfCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.ifCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfCommand([NotNull] MurMurParser.IfCommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.elseCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseCommand([NotNull] MurMurParser.ElseCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.elseCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseCommand([NotNull] MurMurParser.ElseCommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="MurMurParser.endCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndCommand([NotNull] MurMurParser.EndCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MurMurParser.endCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndCommand([NotNull] MurMurParser.EndCommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace MurMur.Grammar
